version: "3.7"

services:
  fapp:
    image: node:alpine
    container_name: fapp
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app